//The Employee.LastPayRaise property is configured 
//to have values generated by the database during updates.
//LastPayRaise被配置未当数据库更新的时候有值产生
modelBuilder.Entity<Employee>()
    .Property(b => b.LastPayRaise)
    .ValueGeneratedOnAddOrUpdate();

modelBuilder.Entity<Employee>()
    .Property(b => b.LastPayRaise)
    .Metadata.AfterSaveBehavior = PropertySaveBehavior.Ignore;